'article_url': 'https://onlinelibrary.wiley.com/doi/10.1111/jofi.13411'
'config_path': './Spider/JFE/config.yml'
'driver_path': 'C:\Users\winger\.wdm\drivers\chromedriver\win64\135.0.7049.42\chromedriver-win32/chromedriver.exe'
'issue_url': 'https://www.sciencedirect.com/journal/journal-of-financial-economics/vol/169/suppl/C'
'save_path': '../../Periodicals/JFE'
